[build]
  command = "composer install && npm install && npm build && php bin/console cache:clear && php bin/console assets:install"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
