[build]
  command = "composer install && php bin/console cache:clear && php bin/console assets:install"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.1"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
