controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: ./login
    controller: App\Controller\AuthController::login
    methods: ['POST']

get_user_inventory:
    path: './api/inventory/{userId}'
    controller: 'App\Controller\InventoryController::getUserInventory'
    methods: ['GET']
